### ISSUE TITLE
WvW key verification add ons?

### ISSUE THREAD

**Issue by DeaJae** [Maselkov/GW2Bot#68]
Is it possible to audit or output a list of who's on what world? ie. ' Nickname - World ' listing to a private channel or DM.
We run a server for a main world/link with now over 1000 people, and while we offer several ways to verify, things slip through, probably not on the ball with people server hopping.  
Even if it automatically sets a named world role when that user's API updates or refreshes by a command will help.

**Comment by Maselkov** [comment]
Were it automatic, it would be need to be a separate script on another server to avoid rate limits (like $bt) as it would need to crawl all accounts for world information (since that information can change, I'm not storing it right now)

More easier way would be via a command, or automatically after using $account. What do you say about those options? Or have any other ideas

**Comment by DeaJae** [comment]
on $account would make sense, but then I guess it won't update if they move servers without doing $account again? I guess that's where the command would come in  
After a few days of thinking about it, there doesn't seem to be much what will work without either a ping/return signal from API or user updating their stuff. Again most users struggled to put their key in the first place.

**Comment by Maselkov** [comment]
I mean, I could make it into a separate script. Another server shouldn't be a problem. Accounts would refresh every few hours if I crawl them.

**Comment by Maselkov** [comment]
$worldsync is now a thing
